commits.message = "[3.0.x] ${artifactName} ${nextVersion} (was ${currentVersion})"

pullRequests.grouping = [
  { name = "patches", "title" = "[3.0.x] Patch updates", "filter" = [{"version" = "patch"}] }
]

# buildRoots does not work because src/main/g8/build.mill is invalid as it was not scaffolded yet.
# E.g. build.mill contains \$ (backslash dollar) which scala-steward / mill can not handle.
# As workaround we use the phantomDeps project in build.sbt
#buildRoots = [ ".", "src/main/g8" ]
