commits.message = "[2.9.x] ${artifactName} ${nextVersion} (was ${currentVersion})"

pullRequests.grouping = [
  { name = "patches", "title" = "[2.9.x] Patch updates", "filter" = [{"version" = "patch"}] }
]

# buildRoots does not work because src/main/g8/build.sc is invalid as it was not scaffolded yet.
# E.g. build.sc contains \$ (backslash dollar) which scala-steward / mill can not handle.
# As workaround we use the phantomDeps project in build.sbt
#buildRoots = [ ".", "src/main/g8" ]

updates.pin = [
  { groupId = "org.scalatestplus.play", artifactId = "scalatestplus-play", version = "6.0." },
  { groupId = "com.typesafe.play", artifactId = "twirl-compiler", version = "1.6." },
  { groupId = "com.typesafe.play", artifactId = "play-routes-compiler", version = "2.9." }
]
