language: scala
scala: 2.13.0

env:
  - TRAVIS_JDK=adopt@1.8.222-10
  - TRAVIS_JDK=adopt@1.11.0-4

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "$TRAVIS_JDK" && jabba use "$_" && java -Xmx32m -version
script: scripts/test-sbt

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.jabba/jdk"
    - "$HOME/.sbt"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete
