language: scala
scala: 2.13.0
script: $SCRIPT

env:
  matrix:
    - SCRIPT=scripts/test-sbt    TRAVIS_JDK=adopt@1.8.212-03
    - SCRIPT=scripts/test-sbt    TRAVIS_JDK=adopt@1.11.0-3
    - SCRIPT=scripts/test-gradle TRAVIS_JDK=adopt@1.8.212-03
    - SCRIPT=scripts/test-gradle TRAVIS_JDK=adopt@1.11.0-3

matrix:
  fast_finish: true
  allow_failures:
    - env: SCRIPT=scripts/test-gradle TRAVIS_JDK=adopt@1.8.212-03 # current gradle doesn't support play 2.7
    - env: SCRIPT=scripts/test-gradle TRAVIS_JDK=adopt@1.11.0-3   # current gradle doesn't support play 2.7

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "$TRAVIS_JDK" && jabba use "$_" && java -Xmx32m -version

cache:
  directories:
    - "$HOME/.gradle/caches"
    - "$HOME/.ivy2/cache"
    - "$HOME/.jabba/jdk"
    - "$HOME/.sbt"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete
