language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

jdk:
  - oraclejdk8

script:
  ## This runs the template with the default parameters, and runs test within the templated app.
  - rm -rf src/main/g8/test # https://github.com/sbt/sbt/issues/630
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test g8Test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
