name: Check

on:
  pull_request:

  push:
    branches:
      - 3.0.x # Check branch after merge

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    uses: playframework/.github/.github/workflows/cmd.yml@v4
    with:
      java: 17, 11
      cmd: sbt test g8Test

  finish:
    name: Finish
    if: github.event_name == 'pull_request'
    needs: # Should be last
      - "tests"
    uses: playframework/.github/.github/workflows/rtm.yml@v4
